version: '2'

services:
  reverse-proxy:
    image: dynamicdevices/balenablock-traefik
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    labels:
      # So that Traefik can listen to the Docker events
      io.balena.features.balena-socket: '1'
